# Generated by Django 3.2.7 on 2021-09-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.TextField(max_length=128, verbose_name='Etkinlik Adı')),
                ('text', models.TextField(max_length=4096, verbose_name='Duyuru Metni')),
                ('banner', models.ImageField(upload_to='', verbose_name='Afiş')),
                ('doing_date', models.DateTimeField()),
            ],
        ),
    ]
